### ISSUE TITLE
Have a cron job that deletes deploys if the PR is closed

### ISSUE THREAD

**Issue by tessereth** [AusDTO/qa-fire#79]
Required if the merge webhook fails for some reason

**Comment by ltankey** [comment]
This should also cascade and delete the cf instance too.

**Comment by ltankey** [comment]
The existing scheduled job could be replaced: instead of checking for consistency with cf - instead check for existing PRs. If an associated CF instance doesn't exist, we can flag the deploy as defunct but _not_ remove it. This gives the user an opportunity to redeploy.
